### ISSUE TITLE
JVX version

### ISSUE THREAD

**Issue by scharf** [sibvisions/jvx.kitchensink#4]
Which version of JVX is packed with this example? And is there a way to figure out which version a `jvx.jar` file is?

**Comment by RobertZenz** [comment]
The version is always noted in the Manifest of the jar file, in this case 2.5.1.

But it would probably be better to add the version to the name of the jar file, to minimize such confusion in the future.

**Comment by RobertZenz** [comment]
I've added the versions to the filenames of the jars.
